import "resource/functions";
auto g=generate("empty");
insert_vertex(g 1);
insert_vertex(g 2);
insert_vertex(g 3);
insert_vertex(g 4);
insert_vertex(g 5);
insert_vertex(g 7);
insert_vertex(g 8);
insert_vertex(g 9);
insert_edge(g 1 2 1);
insert_edge(g 1 3 2);
insert_edge(g 2 4 1);
insert_edge(g 2 5 2);
insert_edge(g 3 7 2);
insert_edge(g 5 8 1);
insert_edge(g 5 9 2);
auto w = display(g);
change_layout(w "binary_tree" 1);